#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Load nvm
export NVM_DIR="/Users/colinmarshall/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Homebrew PHP CLI
# export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

# Load Pear
export PATH="/Users/colinmarshall/pear/bin:$PATH"

#
eval "$(hub alias -s)"
# tabtab source for npm-sync package
# uninstall by removing these lines or running `tabtab uninstall npm-sync`
# [[ -f /Users/colinmarshall/.nvm/versions/node/v8.4.0/lib/node_modules/npm-modules-sync/node_modules/tabtab/.completions/npm-sync.zsh ]] && . /Users/colinmarshall/.nvm/versions/node/v8.4.0/lib/node_modules/npm-modules-sync/node_modules/tabtab/.completions/npm-sync.zsh

export PATH="/usr/local/opt/python/libexec/bin:$PATH"
